"""Add allow_overage

Revision ID: 46fb03f37ec2
Revises: 0a8f0d3ed374
Create Date: 2026-04-06 20:37:57.422742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46fb03f37ec2'
down_revision: Union[str, None] = '0a8f0d3ed374'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('allow_overage', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'allow_overage')
    # ### end Alembic commands ###
