"""Add business_type to workspaces

Revision ID: 4aa1d3ccc53c
Revises: 46fb03f37ec2
Create Date: 2026-04-07 22:22:41.154474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4aa1d3ccc53c'
down_revision: Union[str, None] = '46fb03f37ec2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('business_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'business_type')
    # ### end Alembic commands ###
